server:
  port: 8522
spring:
  ##zipkin配置
  zipkin:
    base-url: http://192.168.174.11:9411/
  sleuth:
    sampler:
      probability: 1 #样本采集量，默认为0.1，为了测试这里修改为1，正式环境一般使用默认值。
  application:
    name: spring-cloud-consul-consumer
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
#ribbon 负载均衡策略配置，service-producer为注册的服务名
service-producer:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
#开启熔断器
feign:
  hystrix:
    enabled: true