server:
  port: 8522
spring:
  application:
    name: spring-cloud-consul-consumer
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: false    #设置不需要注册到 consul 中