server:
  port: 8531
spring:
  application:
    name: spring-cloud-consul-monitor
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
turbine:
  app-config: spring-cloud-consul-consumer # 指定了需要收集监控信息的服务名，多个以“,”进行区分
  instanceUrlSuffix: hystrix.stream #指定收集路径
  cluster-name-expression: "'default'" #指定集群名称，若为default则为默认集群，多个集群则通过此配置区分
  combine-host-port: true # 此配置默认为false，则服务是以host进行区分，若设置为true则以host+port进行区分